apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-helloworld
  namespace: enterprise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-helloworld
  template:
    metadata:
      labels:
        app: tomcat-helloworld
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: tomcat
        image: tomcat-helloworld:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
