name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
      deploy_version:
        description: 'Version to deploy'
        required: false

#on:
#  push:
#    branches:
#      - main
#      - feature/cicd-pipeline

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t tomcat-app:latest .

      # Step 3: Ensure Minikube is running
      - name: Start Minikube if not running
        run: minikube status || minikube start

      # Step 4: Set kubectl context
      - name: Set kubectl context
        run: kubectl config use-context minikube

      # Step 5: Verify cluster
      - name: Verify cluster
        run: kubectl get nodes

      # Step 6: Create namespace
      - name: Create namespace
        run: kubectl apply -f k8s/namespace.yaml

      # Step 7: Deploy PostgreSQL
      - name: Deploy PostgreSQL
        run: |
          kubectl apply -f k8s/postgres-deployment.yaml -n enterprise-app
          kubectl apply -f k8s/postgres-service.yaml -n enterprise-app
          kubectl rollout status deployment/postgres -n enterprise-app

      # Step 8: Get PostgreSQL Pod Name
      - name: Get Postgres Pod
        id: pgpod
        run: |
          POD_NAME=$(kubectl get pods -n enterprise-app -l app=postgres -o jsonpath="{.items[0].metadata.name}")
          echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV

      # Step 9: Create users table in PostgreSQL
      #- name: Create users table
      #  run: |
      #    kubectl exec $POD_NAME -n enterprise-app -- \
      #    psql -U postgres -d mydb -c "
      #    CREATE TABLE IF NOT EXISTS users (
      #        id SERIAL PRIMARY KEY,
      #        name VARCHAR(100) NOT NULL,
      #        age INT CHECK (age >= 0)
      #    );"

      # Step 10: Verify table
      - name: Verify table
        run: |
          kubectl exec $POD_NAME -n enterprise-app -- \
          psql -U postgres -d mydb -c "\dt"

  deploy-tomcat:
    runs-on: self-hosted
    needs: build-and-deploy   # wait for previous job
    environment: production

    steps:

      # Step 11: Apply ConfigMap
      - name: Apply ConfigMap
        run: kubectl apply -f k8s/configmap.yaml -n enterprise-app

      # Step 12: Deploy Tomcat
      - name: Deploy Tomcat
        run: |
          kubectl apply -f k8s/deployment.yaml -n enterprise-app
          kubectl rollout status deployment/tomcat-app -n enterprise-app

      # Step 13: Apply Service
      - name: Apply Service
        run: kubectl apply -f k8s/service.yaml -n enterprise-app
