name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/cicd-pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # GitHub Actions runner

    steps:
      # Step 1: Checkout codes
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t tomcat-app:latest .

      # Step 4: Install kubectl manually (Option 1)
      - name: Install kubectl 1.27.3
        run: |
          curl -LO "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Step 5: Verify kubectl
      - name: Verify kubectl
        run: kubectl version --client

      # Step 6: Create namespace
      - name: Create namespace
        run: kubectl apply -f k8s/namespace.yaml

      # Step 7: Deploy PostgreSQL
      - name: Deploy PostgreSQL
        run: |
          kubectl apply -f k8s/postgres-deployment.yaml -n enterprise-app
          kubectl apply -f k8s/postgres-service.yaml -n enterprise-app
          kubectl rollout status deployment/postgres -n enterprise-app

      # Step 8: Apply ConfigMap
      - name: Apply ConfigMap
        run: kubectl apply -f k8s/configmap.yaml -n enterprise-app

      # Step 9: Deploy Tomcat
      - name: Deploy Tomcat
        run: |
          kubectl apply -f k8s/deployment.yaml -n enterprise-app
          kubectl rollout status deployment/tomcat-app -n enterprise-app

      # Step 10: Apply Tomcat Service
      - name: Apply Service
        run: kubectl apply -f k8s/service.yaml -n enterprise-app
